<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSN2PRLb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSN2PRLb/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSN2PRLb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSN2PRLb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSN2PRLb\App_KernelProdContainer([
    'container.build_hash' => 'SN2PRLb',
    'container.build_id' => 'cea55743',
    'container.build_time' => 1728049929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSN2PRLb');
