<?php
$dictionary["Contact"]["fields"]["b2baccountid"] = array (

            'inline_edit' => '',
            'labelValue' => 'b2baccountid',
            'required' => false,

            'name' => 'b2baccountid',
            'vname' => 'LBL_B2BACCOUNTID',
            'type' => 'int',
            'massupdate' => '0',
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,

);

$dictionary["Contact"]["fields"]["b2bcontactid"] = array (

            'inline_edit' => '',
            'labelValue' => 'b2bcontactid',
            'required' => false,

            'name' => 'b2bcontactid',
            'vname' => 'LBL_B2BCONTACTID',
            'type' => 'int',
            'massupdate' => '0',
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,

);
$dictionary["Contact"]["fields"]["b2b_actioncode"] = array (

            'inline_edit' => '1',
            'labelValue' => 'Action',
            'required' => false,

            'name' => 'b2b_actioncode',
            'vname' => 'LBL_B2B_ACTIONCODE',
            'type' => 'multienum',
            'massupdate' => '0',
            'default' => NULL,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'b2b_actioncode_c_list',
            'studio' => 'visible',
            'isMultiSelect' => true,

);
$dictionary["Contact"]["fields"]["b2b_influencer"] = array (

            'inline_edit' => '1',
            'labelValue' => 'Influence',
            'required' => false,

            'name' => 'b2b_influencer',
            'vname' => 'LBL_B2B_INFLUENCER',
            'type' => 'enum',
            'massupdate' => '0',
            'default' => 'C',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'PMSProfile_type_list',
            'studio' => 'visible',
            'dependency' => false,

);
$dictionary["Contact"]["fields"]["b2b_interests"] = array (

            'inline_edit' => '1',
            'labelValue' => 'Interests',
            'required' => false,

            'name' => 'b2b_interests',
            'vname' => 'LBL_B2B_INTERESTS',
            'type' => 'multienum',
            'massupdate' => '0',
            'default' => NULL,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'b2b_interests_c_list',
            'studio' => 'visible',
            'isMultiSelect' => true,

);
$dictionary["Contact"]["fields"]["b2b_isbooker"] = array (

            'inline_edit' => '1',
            'labelValue' => 'Booker',
            'required' => false,

            'name' => 'b2b_isbooker',
            'vname' => 'LBL_B2B_ISBOOKER',
            'type' => 'bool',
            'massupdate' => '0',
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',

);
$dictionary["Contact"]["fields"]["b2b_language"] = array (

            'inline_edit' => '1',
            'labelValue' => 'Language',
            'required' => false,

            'name' => 'b2b_language',
            'vname' => 'LBL_B2B_LANGUAGE',
            'type' => 'enum',
            'massupdate' => '0',
            'default' => NULL,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'b2b_language_c_list',
            'studio' => 'visible',
            'dependency' => NULL,

);
$dictionary["Contact"]["fields"]["jobcode"] = array (

            'inline_edit' => '1',
            'labelValue' => 'jobcode',
            'required' => false,

            'name' => 'jobcode',
            'vname' => 'LBL_JOBCODE',
            'type' => 'enum',
            'massupdate' => '0',
            'default' => NULL,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'contact_jobcode_list',
            'studio' => 'visible',
            'dependency' => false,

);
$dictionary["Contact"]["fields"]["priority"] = array (

            'inline_edit' => '1',
            'labelValue' => 'Priority',
            'required' => false,

            'name' => 'priority',
            'vname' => 'LBL_PRIORITY',
            'type' => 'enum',
            'massupdate' => '0',
            'default' => NULL,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'contact_priority_list',
            'studio' => 'visible',
            'dependency' => false,

);
$dictionary["Contact"]["fields"]["salesrepcode"] = array (

            'inline_edit' => '1',
            'labelValue' => 'salesrepcode',
            'required' => false,

            'name' => 'salesrepcode',
            'vname' => 'LBL_SALESREPCODE',
            'type' => 'varchar',
            'massupdate' => '0',
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',

);
