<?php
 // created: 2022-10-12 09:19:31
$dictionary['FP_events']['fields']['opportunity'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Opportunity',
    'required' => false,
    'source' => 'non-db',
    'name' => 'opportunity',
    'vname' => 'LBL_OPPORTUNITY',
    'type' => 'relate',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'opportunity_id',
    'ext2' => 'opportunities',
    'module' => 'Opportunities',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
);
 ?>
