<?php

$dictionary["CB2B_AutomatedMonitoring"]["fields"]["schedular"] = array (
    'inline_edit' => '1',
    'labelValue' => 'Schedular',
    'required' => false,
    'source' => 'non-db',
    'name' => 'schedular',
    'vname' => 'LBL_SCHEDULAR',
    'type' => 'relate',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'scheduler_id',
    'ext2' => 'Schedulers',
    'module' => 'Schedulers',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
);

$dictionary["CB2B_AutomatedMonitoring"]["fields"]["scheduler_id"] = array (
    'inline_edit' => 1,
    'required' => false,
    'name' => 'scheduler_id',
    'vname' => 'LBL_SCHEDULAR_SCHEDULER_ID',
    'type' => 'id',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '36',
    'size' => '20',
);