<?php

$dictionary["Lead"]["fields"]["hotel_id"] = array(
    'inline_edit' => '',
    'labelValue' => 'hotel_id',
    'required' => false,
    'name' => 'hotel_id',
    'vname' => 'LBL_HOTEL_ID',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
);
