<?php
$dictionary["Account"]["fields"]["consortia"] = array (
    'inline_edit' => '1',
    'labelValue' => 'consortia',
    'required' => false,
    'name' => 'consortia',
    'vname' => 'LBL_CONSORTIA',
    'type' => 'multienum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'consortia_c_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'id' => 'Accountsconsortia',
);