<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallExtensionAssetsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Command\InstallExtensionAssets' shared autowired service.
     *
     * @return \App\Install\Command\InstallExtensionAssets
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Install'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'InstallExtensionAssets.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Extensions'.\DIRECTORY_SEPARATOR.'ExtensionAssetCopyInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Extensions'.\DIRECTORY_SEPARATOR.'ExtensionAssetCopy.php';

        $container->privates['App\\Install\\Command\\InstallExtensionAssets'] = $instance = new \App\Install\Command\InstallExtensionAssets(($container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopy'] ?? ($container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopy'] = new \App\Engine\Service\Extensions\ExtensionAssetCopy(\dirname(__DIR__, 3)))));

        $instance->setName('scrm:extension-asset-install');

        return $instance;
    }
}
