<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyToFrontendViewDefinitionMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ViewDefinitions\LegacyHandler\LegacyToFrontendViewDefinitionMapper' shared autowired service.
     *
     * @return \App\ViewDefinitions\LegacyHandler\LegacyToFrontendViewDefinitionMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'ViewDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'LegacyToFrontendViewDefinitionMapper.php';

        return $container->privates['App\\ViewDefinitions\\LegacyHandler\\LegacyToFrontendViewDefinitionMapper'] = new \App\ViewDefinitions\LegacyHandler\LegacyToFrontendViewDefinitionMapper($container->parameters['record.fields.legacy_to_frontend_fields_map']);
    }
}
