<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassUpdateActionCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Engine\Service\ActionAvailabilityChecker\Checkers\MassUpdateActionChecker' shared autowired service.
     *
     * @return \App\Engine\Service\ActionAvailabilityChecker\Checkers\MassUpdateActionChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ActionAvailabilityChecker'.\DIRECTORY_SEPARATOR.'ActionAvailabilityCheckerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ActionAvailabilityChecker'.\DIRECTORY_SEPARATOR.'Checkers'.\DIRECTORY_SEPARATOR.'MassUpdateActionChecker.php';

        return $container->privates['App\\Engine\\Service\\ActionAvailabilityChecker\\Checkers\\MassUpdateActionChecker'] = new \App\Engine\Service\ActionAvailabilityChecker\Checkers\MassUpdateActionChecker(($container->privates['App\\ViewDefinitions\\LegacyHandler\\MassUpdateDefinitionHandler'] ?? $container->load('getMassUpdateDefinitionHandlerService')));
    }
}
