<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrationBridgeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\Migrations\MigrationBridge' shared autowired service.
     *
     * @return \App\Install\Service\Migrations\MigrationBridge
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Install'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Migrations'.\DIRECTORY_SEPARATOR.'MigrationBridge.php';

        return $container->privates['App\\Install\\Service\\Migrations\\MigrationBridge'] = new \App\Install\Service\Migrations\MigrationBridge(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['doctrine.migrations.dependency_factory'] ?? $container->load('getDoctrine_Migrations_DependencyFactoryService')));
    }
}
