<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemConfigCollectionDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\SystemConfig\DataProvider\SystemConfigCollectionDataProvider' shared autowired service.
     *
     * @return \App\SystemConfig\DataProvider\SystemConfigCollectionDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'SystemConfig'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'SystemConfigCollectionDataProvider.php';

        return $container->privates['App\\SystemConfig\\DataProvider\\SystemConfigCollectionDataProvider'] = new \App\SystemConfig\DataProvider\SystemConfigCollectionDataProvider(($container->services['app.system-configs'] ?? $container->getApp_SystemconfigsService()));
    }
}
