<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeImagesItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Themes\DataProvider\ThemeImagesItemDataProvider' shared autowired service.
     *
     * @return \App\Themes\DataProvider\ThemeImagesItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Themes'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'ThemeImagesItemDataProvider.php';

        return $container->privates['App\\Themes\\DataProvider\\ThemeImagesItemDataProvider'] = new \App\Themes\DataProvider\ThemeImagesItemDataProvider(($container->privates['App\\Themes\\Service\\ThemeImageService'] ?? $container->load('getThemeImageServiceService')));
    }
}
