<?php

namespace ContainerSN2PRLb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewDefinitionItemDataProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ViewDefinitions\DataProvider\ViewDefinitionItemDataProvider' shared autowired service.
     *
     * @return \App\ViewDefinitions\DataProvider\ViewDefinitionItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'ViewDefinitionItemDataProvider.php';

        return $container->privates['App\\ViewDefinitions\\DataProvider\\ViewDefinitionItemDataProvider'] = new \App\ViewDefinitions\DataProvider\ViewDefinitionItemDataProvider(($container->privates['App\\ViewDefinitions\\LegacyHandler\\ViewDefinitionsHandler'] ?? $container->load('getViewDefinitionsHandlerService')));
    }
}
