<?php

$dictionary["CB2B_PMSProfiles"]['fields']['b2b_account_id'] = array(
    'labelValue' => 'B2B Account ID',
    'required' => false,
    'name' => 'b2b_account_id',
    'vname' => 'LBL_B2B_ACCOUNTID',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
);

$dictionary["CB2B_PMSProfiles"]['fields']['tot_revenue'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Total Revenue',
    'required' => false,
    'name' => 'tot_revenue',
    'vname' => 'LBL_TOT_REVENUE',
    'type' => 'currency',
    'massupdate' => '0',
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '26',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'id' => 'CB2B_PMSProfiles_tot_revenue',
);

$dictionary["CB2B_PMSProfiles"]['fields']['hotel_short_name'] = array(
    'required' => false,
    'name' => 'hotel_short_name',
    'vname' => 'LBL_HOTEL_SHORT_NAME',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'CB2B_PMSProfiles_hotel_short_name',
);

$dictionary["CB2B_PMSProfiles"]['fields']['einsight_pmsprofile_id'] = array(
    'required' => false,
    'name' => 'einsight_pmsprofile_id',
    'vname' => 'LBL_EINSIGHT_PMSPROFILE_ID',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => 'Unique ID for PMS Profile generated in E-Insight',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);

$dictionary["CB2B_PMSProfiles"]['fields']['pms_einsight_profile_id'] = array(
    'required' => false,
    'name' => 'pms_einsight_profile_id',
    'vname' => 'LBL_PMS_EINSIGHT_PROFILE_ID',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => 'Unique ID of PMS Profile carried over to E-Insight',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);

//$dictionary['CB2B_PMSProfiles']['fields']['currency_id'] = array(
//    'inline_edit' => 1,
//    'required' => false,
//    'name' => 'currency_id',
//    'vname' => 'LBL_CURRENCY',
//    'type' => 'currency_id',
//    'massupdate' => '0',
//    'default' => NULL,
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => false,
//    'reportable' => true,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'len' => '36',
//    'size' => '20',
//    'dbType' => 'id',
//    'studio' => 'visible',
//    'function' =>
//    array(
//        'name' => 'getCurrencyDropDown',
//        'returns' => 'html',
//    ),
//);

$dictionary['CB2B_PMSProfiles']['fields']['is_update'] = array(
    'name' => 'is_update',
    'vname' => 'LBL_IS_UPDATE',
    'type' => 'bool',
    'default' => '0',
    'reportable' => false,
    'comment' => 'is_update = 0 in case of Create & is_update = 1 in case of Update & is_update = -1 in case processed by Matching Engine',
);

$dictionary["CB2B_PMSProfiles"]['fields']['first_related_hotel_short_name'] = array(
    'name' => 'first_related_hotel_short_name',
    'vname' => 'LBL_FIRST_RELATED_HOTEL_SHORT_NAME',
    'type' => 'varchar',
    'source' => 'non-db',
    'len' => '255',
    'size' => '20',
);
