<?php


$dictionary["CB2B_PMSProfiles"]['fields']['b2b_account_id'] = array (
    'labelValue' => 'B2B Account ID',
    'required' => false,
    'name' => 'b2b_account_id',
    'vname' => 'LBL_B2B_ACCOUNTID',
    'type' => 'int',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
    'id' => 'CB2B_PMSProfiles_b2b_account_id',
);

$dictionary["CB2B_PMSProfiles"]['fields']['tot_revenue'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Total Revenue',
    'required' => false,
    'name' => 'tot_revenue',
    'vname' => 'LBL_TOT_REVENUE',
    'type' => 'currency',
    'massupdate' => '0',
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '26',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'id' => 'CB2B_PMSProfiles_tot_revenue',
);

$dictionary["CB2B_PMSProfiles"]['fields']['contact_first_name'] = array (
    'required' => false,
    'name' => 'contact_first_name',
    'vname' => 'LBL_CONTACT_FIRST_NAME',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'CB2B_PMSProfiles_contact_first_name',
);

$dictionary["CB2B_PMSProfiles"]['fields']['hotel_short_name'] = array (
    'required' => false,
    'name' => 'hotel_short_name',
    'vname' => 'LBL_HOTEL_SHORT_NAME',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'CB2B_PMSProfiles_hotel_short_name',
);

$dictionary['CB2B_PMSProfiles']['fields']['currency_id'] = array (
    'inline_edit' => 1,
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY',
    'type' => 'currency_id',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '36',
    'size' => '20',
    'dbType' => 'id',
    'studio' => 'visible',
    'function' =>
        array (
            'name' => 'getCurrencyDropDown',
            'returns' => 'html',
        ),
    'id' => 'CB2B_PMSProfiles_currency_id',
);

//
//$dictionary["CB2B_PMSProfiles"]['fields']['b2baccountid'] = array(
//    'labelValue' => 'B2B Account ID',
//    'required' => false,
//    'name' => 'b2baccountid',
//    'vname' => 'LBL_B2BACCOUNTID',
//    'type' => 'int',
//    'massupdate' => '0',
//    'default' => '',
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => false,
//    'reportable' => true,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'len' => '255',
//    'size' => '20',
//    'enable_range_search' => false,
//    'disable_num_format' => '',
//    'min' => false,
//    'max' => false,
//    'id' => 'CB2B_PMSProfilesb2baccountid',
//);
//
//$dictionary["CB2B_PMSProfiles"]['fields']['totrevenue'] = array(
//    'inline_edit' => '1',
//    'labelValue' => 'Total Revenue',
//    'required' => false,
//    'name' => 'totrevenue',
//    'vname' => 'LBL_TOTREVENUE',
//    'type' => 'currency',
//    'massupdate' => '0',
//    'default' => '0',
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => false,
//    'reportable' => true,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'len' => '26',
//    'size' => '20',
//    'enable_range_search' => false,
//    'precision' => 6,
//    'id' => 'CB2B_PMSProfilestotrevenue',
//);
//
//$dictionary["CB2B_PMSProfiles"]['fields']['contactfirstname'] = array (
//    'required' => false,
//    'source' => 'custom_fields',
//    'name' => 'contactfirstname',
//    'vname' => 'LBL_CONTACTFIRSTNAME',
//    'type' => 'varchar',
//    'massupdate' => '0',
//    'default' => NULL,
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => false,
//    'inline_edit' => true,
//    'reportable' => true,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'len' => '255',
//    'size' => '20',
//    'id' => 'CB2B_PMSProfilescontactfirstname',
//);
//
//$dictionary["CB2B_PMSProfiles"]['fields']['hotelshortname'] = array(
//    'required' => false,
//    'name' => 'hotelshortname',
//    'vname' => 'LBL_HOTELSHORTNAME',
//    'type' => 'varchar',
//    'massupdate' => '0',
//    'default' => '',
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'disabled',
//    'duplicate_merge_dom_value' => '0',
//    'audited' => false,
//    'inline_edit' => true,
//    'reportable' => true,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'len' => '255',
//    'size' => '20',
//    'id' => 'CB2B_PMSProfileshotelshortname',
//);